In [1]:
import torch

In [ ]:
torch.accelerator.is_available()

False

In [6]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [16]:
tensor = torch.ones(4,4)
print(tensor[:, 0]) # Column
print(tensor[0]) # Row
print(tensor[...,-1]) #Last column

tensor[:, 1] = 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
torch.cat([tensor, tensor], dim=1) # Concatenate along columns
torch.cat([tensor, tensor], dim=0) # Concatenate along rows

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [19]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [20]:
from torch.utils.data import Dataset
from pathlib import Path
from torchvision.datasets.video_utils import VideoClips


In [3]:
apth = r'data\Brainrot\Brainrot_0.mp4'

In [19]:
import cv2


vid_cap = cv2.VideoCapture(apth)

fps = vid_cap.get(cv2.CAP_PROP_FPS)
total_frames = vid_cap.get(cv2.CAP_PROP_FRAME_COUNT)

print(fps) # Frames per second
print(total_frames) # Total number of frames


# Formula - 16 windows for video and middle fram from each window

window_size = int(total_frames)/ 16
print(window_size)

60.0
3601.0
225.0625


In [22]:
total_frames = int(total_frames)//16
print(total_frames)

0


In [ ]:
while(vid_cap.isOpened()):
  # vid_cap.read() methods returns a tuple, first element is a bool
  # and the second is frame
    vid_cap
    ret, frame = vid_cap.read()
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    current_index = int(vid_cap.get(cv2.CAP_PROP_POS_FRAMES))
    print(current_index)

    just_read_index = current_index - 1
    if just_read_index == 

    break

11


In [ ]:
class CustomDataset(Dataset):
    def __init__(self, data_dir: Path, annotations_file: Path, transform=None):
        self.data_dir = data_dir
        self.annotations_file = annotations_file
        self.transform = transform
        self.video_clips = VideoClips(str(data_dir), clip_length_in_frames=16)

    def __len__(self):
        return len(self.video_clips)

    def __getitem__(self, idx):
        video, _, _, _ = self.video_clips.get_clip(idx)
        return video