In [29]:
import torch
import numpy as np
import cv2
from torch.utils.data import Dataset
from pathlib import Path
from torchvision.datasets.video_utils import VideoClips
import os



In [2]:
torch.accelerator.is_available()

False

In [3]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [4]:
tensor = torch.ones(4,4)
print(tensor[:, 0]) # Column
print(tensor[0]) # Row
print(tensor[...,-1]) #Last column

tensor[:, 1] = 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [5]:
torch.cat([tensor, tensor], dim=1) # Concatenate along columns
torch.cat([tensor, tensor], dim=0) # Concatenate along rows

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [6]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
apth = r'data\Brainrot\Brainrot_0.mp4'

b_dir_path = r'data/Brainrot/'
nb_dir_path = r'data/NonBrainrot/'
nb_files = []
b_files = []
for f in Path(b_dir_path).iterdir():
    if f.is_file():
        b_files.append(str(f))

for f in Path(nb_dir_path).iterdir():
    if f.is_file():
        nb_files.append(str(f))

print(b_files[:10])
print(nb_files[:10])

['data\\Brainrot\\Brainrot_0.mp4', 'data\\Brainrot\\Brainrot_1.mp4', 'data\\Brainrot\\Brainrot_10.mp4', 'data\\Brainrot\\Brainrot_100.mp4', 'data\\Brainrot\\Brainrot_101.mp4', 'data\\Brainrot\\Brainrot_102.mp4', 'data\\Brainrot\\Brainrot_103.mp4', 'data\\Brainrot\\Brainrot_104.mp4', 'data\\Brainrot\\Brainrot_105.mp4', 'data\\Brainrot\\Brainrot_106.mp4']
['data\\NonBrainrot\\NonBrainrot_0.mp4', 'data\\NonBrainrot\\NonBrainrot_1.mp4', 'data\\NonBrainrot\\NonBrainrot_10.mp4', 'data\\NonBrainrot\\NonBrainrot_11.mp4', 'data\\NonBrainrot\\NonBrainrot_12.mp4', 'data\\NonBrainrot\\NonBrainrot_13.mp4', 'data\\NonBrainrot\\NonBrainrot_14.mp4', 'data\\NonBrainrot\\NonBrainrot_15.mp4', 'data\\NonBrainrot\\NonBrainrot_16.mp4', 'data\\NonBrainrot\\NonBrainrot_17.mp4']


In [31]:
b_files[0][-5]

'0'

In [ ]:


def get_video_info(path:str, output_dir:str):

    vid_cap = cv2.VideoCapture(path)
    vid_num = int(path.split('.')[0].split('_')[-1])

    total_frames = vid_cap.get(cv2.CAP_PROP_FRAME_COUNT)
    indx = np.linspace(0, total_frames, num=16, endpoint=True, dtype=int)
    saved_paths = []

    for i in indx:
        vid_cap.set(cv2.CAP_PROP_POS_FRAMES, i)
        ret, frame = vid_cap.read()
        if not ret:
            continue
        frame = cv2.resize(frame, (224, 224))
        frame_path = os.path.join(output_dir, f"{vid_num:02d}_frame_{i:02d}.jpg")
        cv2.imwrite(frame_path, frame)
        saved_paths.append(frame_path)


    print(f"Saved {len(saved_paths)} frames for video {vid_num}")
    vid_cap.release()
    return saved_paths

output_dir = r'data/frames_brairot/'
b_dir_path = r'data/Brainrot/'

for f in Path(b_dir_path).iterdir():
    get_video_info(str(f), output_dir)
    


Saved 15 frames for video 0
Saved 15 frames for video 1
Saved 15 frames for video 10
Saved 15 frames for video 100
Saved 15 frames for video 101
Saved 15 frames for video 102
Saved 15 frames for video 103
Saved 15 frames for video 104
Saved 15 frames for video 105
Saved 15 frames for video 106
Saved 15 frames for video 107
Saved 15 frames for video 108
Saved 15 frames for video 109
Saved 15 frames for video 11
Saved 15 frames for video 110
Saved 15 frames for video 111
Saved 15 frames for video 112
Saved 15 frames for video 113
Saved 15 frames for video 114
Saved 15 frames for video 115
Saved 15 frames for video 116
Saved 15 frames for video 117
Saved 15 frames for video 118
Saved 15 frames for video 119
Saved 15 frames for video 12
Saved 15 frames for video 120
Saved 15 frames for video 121
Saved 15 frames for video 122
Saved 15 frames for video 123
Saved 15 frames for video 124
Saved 15 frames for video 125
Saved 15 frames for video 126
Saved 15 frames for video 127
Saved 15 frames f

In [20]:
vid_cap.set(cv2.CAP_PROP_POS_FRAMES, spacing[1])
vid_cap.get(cv2.CAP_PROP_POS_FRAMES) # Current frame position

240.0

In [12]:
spacing = np.linspace(0, total_frames, num=16, endpoint=True, dtype=int)

print(spacing) # Spacing between frames

[   0  240  480  720  960 1200 1440 1680 1920 2160 2400 2640 2880 3120
 3360 3601]


In [ ]:
while(vid_cap.isOpened()):
  # vid_cap.read() methods returns a tuple, first element is a bool
  # and the second is frame
    vid_cap
    ret, frame = vid_cap.read()
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    current_index = int(vid_cap.get(cv2.CAP_PROP_POS_FRAMES))
    print(current_index)

    just_read_index = current_index - 1
    if just_read_index == 

    break

11


In [ ]:
class CustomDataset(Dataset):
    def __init__(self, data_dir: Path, annotations_file: Path, transform=None):
        self.data_dir = data_dir
        self.annotations_file = annotations_file
        self.transform = transform
        self.video_clips = VideoClips(str(data_dir), clip_length_in_frames=16)

    def __len__(self):
        return len(self.video_clips)

    def __getitem__(self, idx):
        video, _, _, _ = self.video_clips.get_clip(idx)
        return video